services:
  mongo:
    image: mongo:8.0
    container_name: local-mongo
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: appdb

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet --username root --password rootpassword --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 }).ok' localhost:27017/admin | grep 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  mongo-data:
