services:
  app:
    build:
      context: .
    image: "20260811"
    container_name: container-20260811
    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: local
      LOCAL_DB_URL: jdbc:mysql://mysql:3306/appdb
      LOCAL_DB_USERNAME: appuser
      LOCAL_DB_PASSWORD: apppassword
      MONGO_INITDB_ROOT_USERNAME: root
      LOCAL_MONGO_URI: mongodb://root:rootpassword@mongo:27017/appdb?authSource=admin
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

    ports:
      - "8001:8001"
