apiVersion: v1
kind: Service
metadata:
  name: 20260819-svc
  namespace: default
spec:
  selector:
    app: "20260819"
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: LoadBalancer   # Use ClusterIP if only internal access is needed
