apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.application.name | quote }}
  namespace: {{ .Values.application.argocdNamespace | quote }}
spec:
  project: default
  source:
    repoURL: {{ printf "https://github.com/%s.git" .Values.application.repository | quote }}
    targetRevision: {{ .Values.application.branch | quote }}
    path: {{ .Values.application.path | quote }}
    helm:
      releaseName: users-api
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.application.namespace | quote }}
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: {{ .Values.application.deploymentName | quote }}
      namespace: {{ .Values.application.namespace | quote }}
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
