name: Input parameters for workflow dispatch

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - local
          - production
      deploy:
        description: "Deploy application?"
        required: true
        type: boolean
        default: true

jobs:
  deploy_ecs:
    uses: ./.github/workflows/ecs-deploy.yml
    with:
      deploy: ${{ inputs.deploy }}
      environment: ${{ inputs.environment }}
    secrets: inherit
